### ISSUE TITLE
Para realizar os testes que verifiquem a funcionalidade de armazenamento em formatação correta das referências de livro, é necessário encontrar as funções que realizam a conversão de "referencias de livro" para "BibTex" e vice-versa e criar os casos de teste utilizando essas funções.

### ISSUE THREAD

**Issue by iksmada** [iksmada/DC-UFSCar-ES2-201601-GrupoDilema#1]

**Comment by dcardos** [comment]
Seguinte... Não existe bem uma conversão, talvez por isso a dificuldade em encontrar ela. A partir dos campos que o usuário escreve eles já são guardados na classe BibEntry, por exemplo, ao escrever o nome to autor é chamado a função _public void setField(String name, String value)_ (linha 351 da classe BibEntry). 
Com os campos todos salvos a mágica acontece com a classe BibEntryWriter, função da linha 74: _private void writeRequiredFieldsFirstRemainingFieldsSecond(BibEntry entry, Writer out,
            BibDatabaseMode bibDatabaseMode)_
Que escreve na string 'out'. Então basicamente não existe um local para o formato Latex, apenas um buffer que é usado para escrever na tela.
O teste do JUnit BibEntryWriterTest.java da linha 47: _public void testSerialization();_  ilustra esse processo.
