### ISSUE TITLE
Criar nova funcionalidade

### ISSUE THREAD

**Issue by jojima** [iksmada/DC-UFSCar-ES2-201601-GrupoDilema#13]
Desenvolver, implementar e testar uma nova funcionalidade para o JabRef.

**Comment by igorgbianchi** [comment]
Criei uma função para verificar o mês (campo opcional). A entrada deve ser um número entre 1 e 12, a saída é o mês escrito por extenso.

**Comment by igorgbianchi** [comment]
Testes feitos.
