### ISSUE TITLE
Teste funcionais BibiTex Entry

### ISSUE THREAD

**Issue by jojima** [iksmada/DC-UFSCar-ES2-201601-GrupoDilema#9]
Testes de verificação de novas entradas de artigos e livros, devem ser entrados dados e armazenados corretamente.

**Comment by dcardos** [comment]
Testado usando as funções do Igor

**Comment by dcardos** [comment]
Na verdade os testes do Igor não eram o esperado para antes da manutenção, fiz algumas modificações

**Comment by dcardos** [comment]
Os seguintes commits fecham esta issue:
https://github.com/iksmada/DC-UFSCar-ES2-201601-GrupoDilema/commit/395ffaa1c55989428db6e0b1291f39f649d710b1
https://github.com/iksmada/DC-UFSCar-ES2-201601-GrupoDilema/commit/6f99f73aaffa36f0374cd0d323cdeaf48d2348d1
